// USER
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_VERIFICATION = 'USER_VERIFICATION'
export const USER_VERIFICATION_FAILED = 'USER_VERIFICATION_FAILED'
export const USER_FETCH_RESOURCES = 'USER_FETCH_RESOURCES'
export const USER_FETCH_RESOURCES_FAILED = 'USER_FETCH_RESOURCES_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'
