// Character
export const FETCH_CHARACTER = 'FETCH_CHARACTER'
export const FETCH_CHARACTER_FAILED = 'FETCH_CHARACTER_FAILED'
export const FETCH_CHARACTER_LOADING = 'FETCH_CHARACTER_LOADING'
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS'
export const FETCH_CHARACTERS_FAILED = 'FETCH_CHARACTERS_FAILED'
export const FETCH_CHARACTERS_LOADING = 'FETCH_CHARACTERS_LOADING'

// User
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'
export const CREATE_USER_LOADING = 'CREATE_USER_LOADING'
export const AUTHORIZE_USER = 'AUTHORIZE_USER'
export const AUTHORIZE_USER_FAILED = 'AUTHORIZE_USER_FAILED'
export const AUTHORIZE_USER_LOADING = 'AUTHORIZE_USER_LOADING'
export const USER_LOGOUT = 'USER_LOGOUT'
