// USER
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_VERIFICATION = 'USER_VERIFICATION'
export const USER_VERIFICATION_FAILED = 'USER_VERIFICATION_FAILED'
export const USER_FETCH_RESOURCES = 'USER_FETCH_RESOURCES'
export const USER_FETCH_RESOURCES_FAILED = 'USER_FETCH_RESOURCES_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'

// USER-CHARACTERS
export const USER_CHARACTERS = 'USER_CHARACTERS'
export const USER_CHARACTERS_FAILED = 'USER_CHARACTERS_FAILED'
export const USER_CHARACTERS_SELECTED = 'USER_CHARACTERS_SELECTED'
export const USER_CHARACTERS_STATS = 'USER_CHARACTERS_STATS'
export const USER_CHARACTERS_STATS_FAILED = 'USER_CHARACTERS_STATS_FAILED'

// CHARACTERS
export const PROFILE_CHARACTER = 'PROFILE_CHARACTER'
export const PROFILE_CHARACTER_FAILED = 'PROFILE_CHARACTER_FAILED'
export const RANKINGS_CHARACTERS = 'RANKINGS_CHARACTERS'
export const RANKINGS_CHARACTERS_FAILED = 'RANKINGS_CHARACTERS_FAILED'
